title:  Kutama Chamu
tagline:  My school project will be here.
author:
  name: "Chamu Kutama"
  twitter:  Ckutama

menu:
- {name: 'About', url: 'about.html'}
- {name: 'Writing', url: 'writing.html'}
- {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/kutama'}
- {icon: 'twitter', link: 'https://twitter.com/Ckutama'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'envelope', link: 'mailto:norton@kutama.space'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
